CC = gcc
CFLAGS = -Isrc -Itest/unity

test_array_count_sort: test_array_count_sort
	$(CC) $(CFLAGS) test/test_array_count_sort.c src/matrix_view.c \
		src/array_count_sort.c test/unity/src/unity.c \
		-o test/bin/test_array_count_sort
