name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y gcc g++ clang clang-tidy clang-format valgrind cmake make

    - name: Verify Makefile exists
      run: |
        ls -lah Algorithms/C_solutions
        cat Algorithms/C_solutions/Makefile

    - name: Find all C and header files
      id: find_files
      run: |
        FILES=$(find Algorithms/C_solutions -type f \( -name '*.c' -o -name '*.h' \))
        echo "FILES=$FILES" >> $GITHUB_ENV

    - name: Run Clang-Format
      run: |
        echo "$FILES" | xargs clang-format -i --verbose
  
    - name: Run Clang-Tidy
      run: |
        cd Algorithms/C_solutions
        clang-tidy $FILES -- -IAlgorithms/C_solutions/include -IAlgorithms/C_solutions/src/headers || true

    - name: Run GCC Debug Build with Valgrind
      run: |
        cd Algorithms/C_solutions
        make
        valgrind --quiet --leak-check=full --error-exitcode=123 ./test/bin/all_tests || exit 1
  
    - name: Build and Run Tests
      run: |
        cd Algorithms/C_solutions
        make
        if make | grep -q 'Tests Failed: 0'; then
          echo "All tests passed!"
        else
          echo "Some tests failed!"
          exit 1
        fi

    - name: Check for errors in build
      run: |
        if [ $? -ne 0 ]; then
          echo "Error in the build process"
          exit 1
        fi