name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y gcc make

    - name: Verify Makefile exists
      run: |
        ls -lah Algorithms/C_solutions
        cat Algorithms/C_solutions/Makefile

    - name: Build and Run Tests
      run: |
        cd Algorithms/C_solutions
        make
        if make | grep -q 'Tests Failed: 0'; then
          echo "All tests passed!"
        else
          echo "Some tests failed!"
          exit 1
        fi

    - name: Check for errors in build
      run: |
        if [ $? -ne 0 ]; then
          echo "❌ Error in the build process"
          exit 1
        fi
