# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      python-path: ${{ steps.set-python-path.outputs.python-path }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      id: python-setup
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Lint with flake8
      run: |
        source ./venv/bin/activate
        flake8 --config=./config ./Algorithms/python_solutions

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests with coverage
      run: |
        coverage run
    - name: Check tests coverage
      run: |
        coverage report -m

  docs:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Check docs coverage
      run: |
        interrogate ./Algorithms/python_solutions

  security:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Check issues with bandit
      run: |
        bandit ./Algorithms/python_solutions/* -b bandit.json -ll
